name: Integration Test Reusable (backend)

on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
      target:
        required: true
        type: string

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: instill-ai/vdp

      - name: Load .env file
        uses: cardinalby/export-env-action@v2
        with:
          envFile: .env
          expand: true

      # mono occupies port 8084 which conflicts with mgmt-backend
      - name: Stop mono service
        run: |
          sudo kill -9 `sudo lsof -t -i:8084`
          sudo lsof -i -P -n | grep LISTEN

      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v${{ env.K6_VERSION }}/k6-v${{ env.K6_VERSION }}-linux-amd64.tar.gz -L | tar xvz --strip-components 1 && sudo cp k6 /usr/bin

      - name: Free disk space
        run: |
          df --human-readable
          sudo apt clean
          docker rmi $(docker image ls --all --quiet)
          rm --recursive --force "$AGENT_TOOLSDIRECTORY"
          df --human-readable

      - name: Launch VDP (${{ inputs.target }})
        run: |
          COMPOSE_PROFILES=all \
          EDITION=${{ inputs.target }} \
          ITMODE=true \
          TRITON_CONDA_ENV_PLATFORM=cpu \
          docker compose -f docker-compose.yml -f docker-compose.edition.yml up -d --quiet-pull
          COMPOSE_PROFILES=all \
          EDITION=${{ inputs.target }} \
          docker compose -f docker-compose.yml -f docker-compose.edition.yml rm -f

      - name: Run ${{ inputs.component }}-backend integration test (${{ inputs.target }})
        run: |
          git clone https://github.com/instill-ai/${{ inputs.component }}-backend.git ${{ inputs.component }}-backend
          cd ${{ inputs.component }}-backend
          make integration-test EDITION=${{ inputs.target }} MODE=localhost
