name: Integration Test Reusable (console)

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: instill-ai/vdp

      - name: Load .env file
        uses: cardinalby/export-env-action@v2
        with:
          envFile: .env
          expand: true

      # mono occupies port 8084 which conflicts with mgmt-backend
      - name: Stop mono service
        run: |
          sudo kill -9 `sudo lsof -t -i:8084`
          sudo lsof -i -P -n | grep LISTEN

      - name: Free disk space
        run: |
          df --human-readable
          sudo apt clean
          docker rmi $(docker image ls --all --quiet)
          rm --recursive --force "$AGENT_TOOLSDIRECTORY"
          df --human-readable

      - name: Launch VDP (${{ inputs.target }})
        run: |
          COMPOSE_PROFILES=all \
          EDITION=${{ inputs.target }} \
          ITMODE=true \
          TRITON_CONDA_ENV_PLATFORM=cpu \
          CONSOLE_BASE_URL_HOST=console \
          CONSOLE_BASE_API_GATEWAY_URL_HOST=api-gateway \
          docker compose -f docker-compose.yml -f docker-compose.edition.yml up -d --quiet-pull
          COMPOSE_PROFILES=all \
          EDITION=${{ inputs.target }} \
          docker compose -f docker-compose.yml -f docker-compose.edition.yml rm -f
      - name: Run console integration test (${{ inputs.target }})
        run: |
          git clone https://github.com/instill-ai/console.git console
          cd console && docker build --build-arg TEST_USER='root' -f Dockerfile.playwright -t console-playwright .
          docker run -t --rm \
            -e NEXT_PUBLIC_CONSOLE_BASE_URL=http://console:3000 \
            -e NEXT_PUBLIC_API_GATEWAY_BASE_URL=http://api-gateway:8080 \
            -e NEXT_SERVER_API_GATEWAY_BASE_URL=http://api-gateway:8080 \
            -e NEXT_PUBLIC_API_VERSION=v1alpha \
            -e NEXT_PUBLIC_SELF_SIGNED_CERTIFICATION=false \
            -e NEXT_PUBLIC_INSTILL_AI_USER_COOKIE_NAME=instill-ai-user \
            --network instill-network \
            --entrypoint ./entrypoint-playwright.sh \
            --name console-integration-test console-playwright
      - name: Launch VDP (rc)
        if: inputs.target == 'rc'
        run: |
          COMPOSE_PROFILES=all \
          EDITION=local-ce:test \
          ITMODE=true \
          TRITON_CONDA_ENV_PLATFORM=cpu \
          CONSOLE_BASE_URL_HOST=console \
          CONSOLE_BASE_API_GATEWAY_URL_HOST=api-gateway \
          docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --quiet-pull
          COMPOSE_PROFILES=all \
          docker compose -f docker-compose.yml -f docker-compose.dev.yml rm -f
      - name: Run console integration test (rc)
        if: inputs.target == 'rc'
        run: |
          git clone https://github.com/instill-ai/console.git console
          cd console && docker build --build-arg TEST_USER='root' -f Dockerfile.playwright -t console-playwright .
          docker run -t --rm \
            -e NEXT_PUBLIC_CONSOLE_BASE_URL=http://console:3000 \
            -e NEXT_PUBLIC_API_GATEWAY_BASE_URL=http://api-gateway:8080 \
            -e NEXT_SERVER_API_GATEWAY_BASE_URL=http://api-gateway:8080 \
            -e NEXT_PUBLIC_API_VERSION=v1alpha \
            -e NEXT_PUBLIC_SELF_SIGNED_CERTIFICATION=false \
            -e NEXT_PUBLIC_INSTILL_AI_USER_COOKIE_NAME=instill-ai-user \
            --network instill-network \
            --entrypoint ./entrypoint-playwright.sh \
            --name console-integration-test console-playwright
